const assert = require("node:assert/strict")
const fs = require("node:fs")
const os = require("node:os")
const path = require("node:path")
const { updateHooks } = require("../../scripts/codex-island-hook.cjs")

const directory = fs.mkdtempSync(path.join(os.tmpdir(), "island-hook-install-"))
const target = path.join(directory, "hooks.json")
try {
  assert.equal(updateHooks(directory, true), false)
  assert.equal(fs.existsSync(target), false, "removal does not create hooks.json")
  const original = JSON.stringify({ description: "User configuration" })
  fs.writeFileSync(target, original)
  assert.equal(updateHooks(directory, true), false)
  assert.equal(fs.readFileSync(target, "utf8"), original, "unrelated config remains byte-identical")
  const userHook = { matcher: "Bash", hooks: [{ type: "command", command: "user-command" }] }
  fs.writeFileSync(target, JSON.stringify({ hooks: { PreToolUse: [userHook] } }))
  assert.equal(updateHooks(directory, false), true)
  const installed = fs.readFileSync(target, "utf8")
  assert.deepEqual(JSON.parse(installed).hooks.PreToolUse[0], userHook)
  assert.equal(updateHooks(directory, false), false, "repeated installation is a no-op")
  assert.equal(fs.readFileSync(target, "utf8"), installed)
  assert.equal(updateHooks(directory, true), true)
  assert.deepEqual(JSON.parse(fs.readFileSync(target, "utf8")).hooks.PreToolUse, [userHook])
  const removed = fs.readFileSync(target, "utf8")
  assert.equal(updateHooks(directory, true), false)
  assert.equal(fs.readFileSync(target, "utf8"), removed)
  fs.writeFileSync(target, "malformed")
  assert.throws(() => updateHooks(directory, false))
  assert.equal(fs.readFileSync(target, "utf8"), "malformed", "invalid configuration is never replaced")
  assert.ok(fs.readdirSync(directory).some(name => name.includes("island-backup-")), "replacement retains a recovery copy")
  console.log("hook install/remove round-trip passed on an owned temporary directory; user Codex configuration untouched")
} finally {
  for (const name of fs.readdirSync(directory)) fs.unlinkSync(path.join(directory, name))
  fs.rmdirSync(directory)
}
